name: MonkeySoft API HML EC2

on:
  pull_request:
    types:
      - closed
    branches:
      - "*"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    permissions: write-all
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Notify start on Discord
        env:
          WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": ":yellow_circle:\n'"$(basename $GITHUB_REPOSITORY)"'\nBranch: **${{ github.ref_name }}**\nWorkflow: '"${GITHUB_SERVER_URL}"'/'"${GITHUB_REPOSITORY}"'/actions/runs/'"${GITHUB_RUN_ID}"' "}' $WEBHOOK_URL

      - name: Check branch name
        run: |
          BRANCH_BASE_NAME=${{ github.base_ref }}
          echo "Nome da branch de destino: $BRANCH_BASE_NAME"
          if [[ $BRANCH_BASE_NAME =~ ^release-r([1-9]|1[0-2])-[0-9]{4}$ ]]; then
            echo "Branch name matches the pattern"
          else
            echo "Branch name does not match the pattern"
            exit 1
          fi

      # - name: Checkout files
      #   uses: actions/checkout@v4

      # - name: Install dependencies
      #   run: npm install

      # - name: Build application
      #   run: npm run build

      # - name: Run test and coverage
      #   run: npm run coverage

      - name: Update version
        run: |
          BRANCH_HEAD_NAME=${{ github.base_ref }}
          echo "Nome da branch de origem: $BRANCH_HEAD_NAME"
          PREFIX=$(echo $BRANCH_HEAD_NAME | cut -d '/' -f 1)
          echo "Prefixo da branch: $PREFIX"

          if [ "$PREFIX" == "feat" ]; then
            echo "Atualizando versão com minor"
          elif [ "$PREFIX" == "fix" ]; then
            echo "Atualizando versão com patch"
          else
            echo "Branch name does not match the pattern"
            exit 1
          fi

      # - name: Get new version
      #   run: echo "PACKAGE_VERSION=$(node -pe 'require("./package.json").version')" >> $GITHUB_ENV

      # - name: Prepare Environment Files
      #   run: |
      #     echo "PORT=${{vars.PORT_HML}}" >> .env
      #     echo "DB_HOST=${{secrets.DB_HOST_HML}}" >> .env
      #     echo "DB_PORT=${{secrets.DB_PORT_HML}}" >> .env
      #     echo "DB_USER=${{secrets.DB_USER_HML}}" >> .env
      #     echo "DB_PASS=${{secrets.DB_PASS_HML}}" >> .env

      # - name: Prepare Pm2 Environment File
      #   run: |
      #     echo "module.exports = {apps : [{name: \"monkeysoft-api\",script : \"dist/index.js\"}]}" >> ./dist/.pm2.config.js

      # - name: Transfer files to EC2
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{secrets.EC2_HOST_HML}}
      #     username: ${{secrets.EC2_USER_HML}}
      #     key: ${{secrets.EC2_PRIVATE_KEY_HML}}
      #     port: ${{secrets.EC2_PORT_HML}}
      #     source: "./dist,package.json,.env"
      #     target: ${{secrets.TARGET_DIR}}

      # - name: Transfer files to EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.EC2_HOST_HML}}
      #     username: ${{secrets.EC2_USER_HML}}
      #     key: ${{secrets.EC2_PRIVATE_KEY_HML}}
      #     port: ${{secrets.EC2_PORT_HML}}
      #     script: |
      #       cd /home/ubuntu/monkeysoft-api
      #       npm install
      #       sudo pm2 start ./dist/.pm2.config.js
      #       sudo pm2 save

      - name: Notify error to Discord
        if: failure()
        env:
          WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": ":red_circle:\n'"$(basename $GITHUB_REPOSITORY)"' **'"${PACKAGE_VERSION}"'**\nBranch: **${{ github.ref_name }}**\nWorkflow: '"${GITHUB_SERVER_URL}"'/'"${GITHUB_REPOSITORY}"'/actions/runs/'"${GITHUB_RUN_ID}"' "}' $WEBHOOK_URL

      - name: Notify success to Discord
        if: success()
        env:
          WEBHOOK_URL: ${{secrets.DISCORD_WEBHOOK_URL}}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": ":green_circle:\n'"$(basename $GITHUB_REPOSITORY)"' **'"${PACKAGE_VERSION}"'**\nBranch: **${{ github.ref_name }}**\nWorkflow: '"${GITHUB_SERVER_URL}"'/'"${GITHUB_REPOSITORY}"'/actions/runs/'"${GITHUB_RUN_ID}"' "}' $WEBHOOK_URL
